# All options listed are currently set to their default values
[options]
# Path where the profile will be read from/stored
profile_path = "profile.json"

# When true, prints every time you catch something
print_output = false

# The message sent when you join a server
greet_message = "><(((('> AFK Fishing... ><(((('>"

# The message sent when you join a server to inform other players of the sleep functionality
sleep_message = "Type '{sleep_command}' to log me off for {sleep_time} seconds"

# The command other players must send to activate sleep-mode
sleep_command = "sleep"

# Amount of seconds the client will log off to allow sleeping.
sleep_time = 10

# When false, ignore sleep-requests
sleep_helper = true

# Timeout in seconds
fish_timeout = 120

# Username to use when joining a server in offline mode
username = "fisherman"


[host]
# Set to true if you wish to connect to a realm
realm = true

# The name of the realm
realm_name = "my realm"

# Minecraft version to connect with. Defaults to the latest avaliable release in pyCraft
version = "1.13"

