### Options that are commented out are listed with their default value
[options]
### Path where the profile will be read from/stored
#profile_path = "profile.json"

### When true, prints every time you catch something
#print_output = false

### The message sent when you join a server. Set to an empty string to disable.
#greet_message = "><(((('> AFK Fishing... ><(((('>"

### The message sent when you join a server to inform other players of the sleep functionality
#sleep_message = "Type '{sleep_command}' to log me off for {sleep_time} seconds"

### The command other players must send to activate sleep-mode
#sleep_command = "sleep"

### Amount of seconds the client will log off to allow sleeping.
#sleep_time = 10

### When false, ignore sleep-requests
#sleep_helper = true

### Time in seconds before the script assumes something has gone wrong and attempts to cast again
### In versions 1.7.2 and greater this should be at least 30 seconds
### In versions 1.2.0 - 1.7.1, 60 seconds yields a 9% chance that an attempt that would have
### succeeded will be interrupted, while 120 seconds yields a 0.8% chance.
#fish_timeout = 60

### Username to use when joining a server in offline mode
### This option does NOT have a default
# username = "fisherman"


[host]
### Address to the server, either an ip or a hostname
### This option does NOT have a default
address = "127.0.0.1"

### Port of the server, usually 25565
#port = "25565"

### Minecraft version to connect with.
### Defaults to the latest avaliable release in pyCraft
#version = "1.15.2"

### Whether or not to play in offline mode. When true, no authentication is required
#offline = false
